In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
#sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
        ]

In [5]:
voc_size = 10000

In [6]:
#OneHot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6679, 3694, 4702, 1055],
 [6679, 3694, 4702, 532],
 [6679, 6796, 4702, 6545],
 [7786, 8276, 5776, 212, 6507],
 [7786, 8276, 5776, 212, 1642],
 [4570, 6679, 6171, 4702, 2334],
 [35, 7999, 9523, 212]]

In [7]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
#pre--> 0's before
#post--> 0's after

[[   0    0    0    0 6679 3694 4702 1055]
 [   0    0    0    0 6679 3694 4702  532]
 [   0    0    0    0 6679 6796 4702 6545]
 [   0    0    0 7786 8276 5776  212 6507]
 [   0    0    0 7786 8276 5776  212 1642]
 [   0    0    0 4570 6679 6171 4702 2334]
 [   0    0    0    0   35 7999 9523  212]]


In [9]:
#feature representation
import warnings
warnings.filterwarnings('ignore')
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_length))
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 334ms/step


array([[[-0.04231029, -0.01746891, -0.03974367, -0.0368989 ,
         -0.00983615, -0.02180582,  0.01149612,  0.02720268,
          0.02691281, -0.01148782],
        [-0.04231029, -0.01746891, -0.03974367, -0.0368989 ,
         -0.00983615, -0.02180582,  0.01149612,  0.02720268,
          0.02691281, -0.01148782],
        [-0.04231029, -0.01746891, -0.03974367, -0.0368989 ,
         -0.00983615, -0.02180582,  0.01149612,  0.02720268,
          0.02691281, -0.01148782],
        [-0.04231029, -0.01746891, -0.03974367, -0.0368989 ,
         -0.00983615, -0.02180582,  0.01149612,  0.02720268,
          0.02691281, -0.01148782],
        [ 0.02985242,  0.01682505,  0.01179092, -0.00236138,
         -0.04421041, -0.04599836, -0.04327399,  0.04772845,
         -0.03457483,  0.03139849],
        [-0.04228169,  0.02984026, -0.04170866, -0.0230161 ,
          0.00198343,  0.04518194,  0.03290286,  0.00222676,
          0.02583719,  0.03704958],
        [ 0.01096068,  0.00740035,  0.04367678,  0.0